version: '3'

services:
        csvserver-service:
                image: infracloudio/csvserver:latest
                volumes:
                - ./inputFile:/csvserver/inputdata
                ports:
                - 9393:9300
                environment:
                - CSVSERVER_BORDER=Orange
